version: "3.8"

services:
  redis:
    restart: always
    container_name: redis
    image: redis:latest
  
  web:
    restart: always
    container_name: web
    build: ./web/
    volumes:
      - ./web:/web

  db:
    restart: always
    container_name: db
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ./postgre:/var/lib/postgresql/data

  nginx:
    restart: always
    build: ./nginx/
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./web/staticfiles:/web/staticfiles